version: '3.8'

services:
  # AI问答系统主服务
  ai-wenda:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-wenda-app
    ports:
      - "8081:8081"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      # 数据持久化
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
      # 数据库文件持久化
      - ./data/databases:/app/databases
    restart: unless-stopped
    networks:
      - ai-wenda-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis缓存服务 (可选)
  redis:
    image: redis:7-alpine
    container_name: ai-wenda-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - ai-wenda-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: ai-wenda-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - ai-wenda
    restart: unless-stopped
    networks:
      - ai-wenda-network
    profiles:
      - production

  # 监控服务 (可选)
  prometheus:
    image: prom/prometheus:latest
    container_name: ai-wenda-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - ai-wenda-network
    profiles:
      - monitoring

volumes:
  redis-data:
    driver: local
  prometheus-data:
    driver: local

networks:
  ai-wenda-network:
    driver: bridge